name: build

on: [push, pull_request]

jobs:
    ubuntu:
        runs-on: [ubuntu-latest]
        strategy:
            matrix:
                java: [21]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'liberica'

            - name: Prepare certificates and provisioning (Linux)
              run: |
                  printf "%s\n" "${{ secrets.CERT_PEM }}" > certificate.pem
                  printf "%s\n" "${{ secrets.PRIVATE_KEY }}" > private.key
                  chmod 600 private.key
                  cat > provision.json <<EOF
                  [
                    {
                      "description": "Instala mi root CA",
                      "type": "ca",
                      "data": "certificate.pem"
                    },
                    {
                      "description": "Confía en el certificado de QZ Tray",
                      "type": "cert",
                      "data": "certificate.pem"
                    },
                    {
                      "description": "Despliega la clave privada",
                      "type": "script",
                      "phase": "install",
                      "os": "linux",
                      "data": "deploy_key.sh"
                    }
                  ]
                  EOF

            - run: sudo apt-get install nsis makeself
            - run: ant makeself
            - run: sudo out/qz-tray-*.run
            - run: /opt/qz-tray/qz-tray --version
            - run: ant nsis

            - name: Upload installers as artifact
              uses: actions/upload-artifact@v4
              with:
                name: installers-linux-java${{ matrix.java }}
                path: out/qz-tray-*

    macos:
        runs-on: [macos-latest]
        strategy:
            matrix:
                java: [21]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'liberica'

            - name: Prepare certificates and provisioning (macOS)
              run: |
                  printf "%s\n" "${{ secrets.CERT_PEM }}" > certificate.pem
                  printf "%s\n" "${{ secrets.PRIVATE_KEY }}" > private.key
                  chmod 600 private.key
                  cat > provision.json <<EOF
                  [
                    {
                      "description": "Instala mi root CA",
                      "type": "ca",
                      "data": "certificate.pem"
                    },
                    {
                      "description": "Confía en el certificado de QZ Tray",
                      "type": "cert",
                      "data": "certificate.pem"
                    },
                    {
                      "description": "Despliega la clave privada",
                      "type": "script",
                      "phase": "install",
                      "os": "mac",
                      "data": "deploy_key.sh"
                    }
                  ]
                  EOF

            - run: brew install nsis makeself
            - run: ant pkgbuild
            - run: echo "Setting CA trust settings to 'allow' (https://github.com/actions/runner-images/issues/4519)"
            - run: security authorizationdb read com.apple.trust-settings.admin > /tmp/trust-settings-backup.xml
            - run: sudo security authorizationdb write com.apple.trust-settings.admin allow
            - run: sudo installer -pkg out/qz-tray-*.pkg -target /
            - run: echo "Restoring CA trust settings back to default"
            - run: sudo security authorizationdb write com.apple.trust-settings.admin < /tmp/trust-settings-backup.xml
            - run: "'/Applications/QZ Tray.app/Contents/MacOS/QZ Tray' --version"
            - run: ant makeself
            - run: ant nsis

            - name: Upload installers as artifact
              uses: actions/upload-artifact@v4
              with:
                name: installers-macos-java${{ matrix.java }}
                path: out/qz-tray-*

    windows:
        runs-on: [windows-latest]
        strategy:
            matrix:
                java: [21]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'liberica'

            - name: Prepare certificates and provisioning (Windows)
              shell: pwsh
              run: |
                  Write-Output "${{ secrets.CERT_PEM }}" | Out-File -Encoding ascii certificate.pem
                  Write-Output "${{ secrets.PRIVATE_KEY }}" | Out-File -Encoding ascii private.key
                  $json = @'
                  [
                    {
                      "description": "Instala mi root CA",
                      "type": "ca",
                      "data": "certificate.pem"
                    },
                    {
                      "description": "Confía en el certificado de QZ Tray",
                      "type": "cert",
                      "data": "certificate.pem"
                    },
                    {
                      "description": "Despliega la clave privada",
                      "type": "script",
                      "phase": "install",
                      "os": "windows",
                      "data": "deploy_key.sh"
                    }
                  ]
                  '@
                  $json | Out-File -FilePath provision.json -Encoding ascii

            - run: choco install nsis
            - run: ant nsis
            - run: Start-Process -Wait ./out/qz-tray-*.exe -ArgumentList "/S"
            - run: "&'C:/Program Files/QZ Tray/qz-tray.exe' --wait --version|Out-Null"
            
            - name: Upload installers as artifact
              uses: actions/upload-artifact@v4
              with:
                name: installers-windows-java${{ matrix.java }}
                path: out/qz-tray-*

