name: Build QZ Tray Installers

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                java: [21]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: ${{ matrix.java }}

            - name: Install dependencies
              run: |
                  if [[ "${{ runner.os }}" == "Linux" ]]; then
                    sudo apt-get update && sudo apt-get install -y ant
                  elif [[ "${{ runner.os }}" == "macOS" ]]; then
                    brew update && brew install ant nsis
                  else
                    choco install -y ant nsis
                  fi

            - name: Inject certificates from Secrets
              run: |
                  printf "%s\n" "${{ secrets.CERT_PEM }}" > certificate.pem
                  printf "%s\n" "${{ secrets.PRIVATE_KEY }}" > private.key
                  chmod 600 private.key

            - name: Copy provisioning files
              run: |
                  cp deploy_key.sh .
                  cat > provision.json <<EOF
                  [
                    {
                      "description": "Instala mi root CA",
                      "type": "ca",
                      "data": "certificate.pem"
                    },
                    {
                      "description": "Confía en el certificado de QZ Tray",
                      "type": "cert",
                      "data": "certificate.pem"
                    },
                    {
                      "description": "Despliega la clave privada",
                      "type": "script",
                      "phase": "install",
                      "os": "windows|mac|linux",
                      "data": "deploy_key.sh"
                    }
                  ]
                  EOF

            - name: Build installers
              run: |
                  ant -Dprovision.file=provision.json
                  ant -Dprovision.file=provision.json nsis
                  ant -Dprovision.file=provision.json pkgbuild
                  ant -Dprovision.file=provision.json makeself

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: installers-${{ matrix.os }}
                  path: out/qz-tray-*
